# Generated by Django 3.1.3 on 2020-11-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='address',
            field=models.CharField(default='aaa', max_length=200, verbose_name='주소'),
            preserve_default=False,
        ),
    ]
